alias: 'Calefacció dormitori - Configurar 19.5ºC'
initial_state: true
trigger:
  - platform: time
    at: "21:30:00"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: time
      after: "15:00:00"
    - condition: time
      before: "23:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.dormitori
      temperature: 19.5