alias: 'Calefacció dormitori - Apagar (feiners)'
initial_state: true
trigger:
  - platform: time
    at: "08:30:00"
  - platform: state
    entity_id: switch.calefaccio_dormitori
    from: "on"
    to: "off"
condition:
  condition: and
  conditions:
    - condition: time
      after: "07:30:00"
      before: "09:30:00"
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.festius_barcelona
      state: 'on'
action:
  - service: climate.turn_off
    entity_id: climate.dormitori