alias: 'Set menjador climate to 18 at night'
initial_state: true
trigger:
  - platform: time
    at: "23:00:00"
condition:
  - condition: state
    entity_id: climate.menjador
    state: 'heat'
action:
  - service: climate.set_temperature
    entity_id: climate.menjador
    data:
      temperature: 18.5