alias: 'Set dormitori climate to 19 at afternoon'
initial_state: true
trigger:
  - platform: time_pattern
    minutes: "/5"
condition:
  condition: and
  conditions:
    - condition: time
      after: "22:00:00"
      before: "22:59:00"
    - condition: numeric_state
      entity_id: sensor.exterior_temperature_mqtt
      below: 15
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.tele
          state: 'playing'
        - condition: state
          entity_id: light.encimera
          state: 'on'
        - condition: state
          entity_id: light.entrada
          state: 'on'
        - condition: state
          entity_id: light.mesa
          state: 'on'
        - condition: state
          entity_id: light.sofa
          state: 'on'
action:
  - service: climate.set_temperature
    entity_id: climate.dormitori
    data:
      temperature: 19
  - service: climate.turn_on
    entity_id: climate.dormitori