alias: 'Set menjador climate to 19 at afternoon'
initial_state: true
trigger:
  - platform: time_pattern
    minutes: "/5"
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
      after_offset: "01:00:00"
    - condition: state
      entity_id: climate.menjador
      state: "off"
    - condition: time
      before: "22:59:00"
    - condition: numeric_state
      entity_id: sensor.exterior_temperature_mqtt
      below: 15
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.tele
          state: 'playing'
        - condition: state
          entity_id: light.encimera
          state: 'on'
        - condition: state
          entity_id: light.entrada
          state: 'on'
        - condition: state
          entity_id: light.mesa
          state: 'on'
        - condition: state
          entity_id: light.sofa
          state: 'on'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.menjador
      temperature: 19
  - service: climate.turn_on
    data:
      entity_id: climate.menjador