alias: 'Calefacció menjador - Configurar 19.5ºC'
initial_state: false
trigger:
  - platform: sun
    event: sunset
    offset: "00:30:00"
  - platform: time
    at: "19:00:00"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: time
      after: "15:00:00"
      before: "23:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.menjador
      temperature: 19.5
