alias: 'Calefacció menjador - Configurar 18.5ºC'
initial_state: true
trigger:
  - platform: time
    at: "23:00:00"
  - platform: homeassistant
    event: start
condition:
  - condition: time
    after: "22:59:00"
    before: "01:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.menjador
      temperature: 18.5
