alias: 'Calefacció menjador - Configurar 19.0ºC'
initial_state: false
trigger:
  - platform: time
    at: "06:30:00"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: time
      after: "06:30:00"
      before: "08:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.menjador
      temperature: 19.0
  - service: climate.turn_on
    data:
      entity_id: climate.menjador