alias: 'Calefacció menjador - Engegar'
initial_state: false
trigger:
  - platform: sun
    event: sunset
    offset: "00:15:00"
  - platform: time
    at: "19:00:00"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
    - condition: time
      before: "23:00:00"
    # - condition: numeric_state
    #   entity_id: sensor.exterior_temperature_mqtt
    #   below: 15
    - condition: template
      value_template: "{{ is_state('person.imma', 'home') or is_state('person.aleix', 'home')  }}"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.menjador