- id: '1605114430857'
  alias: Encendre llum quan es fa fosc
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.aleix
      state: home
    - condition: state
      entity_id: person.imma
      state: home
  - condition: device
    type: is_off
    device_id: a2047eca41ad452f87b58ae94d6702df
    entity_id: light.mesita
    domain: light
  action:
  - scene: scene.tele
  mode: single
- id: '1613040447539'
  alias: Rice cooker
  description: ''
  trigger:
  - platform: time
    at: '13:30'
  condition: []
  action:
  - type: turn_on
    device_id: 8ec91fd540e8abad027240dfefe73885
    entity_id: switch.arbre_nadal
    domain: switch
  mode: single
- id: '1613040503874'
  alias: Rice cooker
  description: ''
  trigger:
  - platform: time
    at: '13:30'
  condition: []
  action:
  - type: turn_on
    device_id: 8ec91fd540e8abad027240dfefe73885
    entity_id: switch.arbre_nadal
    domain: switch
  mode: single
