# Config needed to work

homeassistant:
  name: Casa
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 102
  unit_system: metric
  time_zone: Europe/Madrid
  # customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp/

logger:
  default: info
  logs:
    custom_components.beewi_smartclim.sensor: debug

config:

system_health:

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: casa.aleix.cloud

history:

recorder:
  purge_keep_days: 7
  purge_interval: 1

logbook:

api:

auth:

duckdns:
  domain: hass-amurtra
  access_token: !secret duckdns_api_key

lovelace:
  mode: yaml

person:
  - name: Aleix
    id: aleix
    user_id: 23b5a590030a4d5b907d0f5675e75e3e
    device_trackers:
      - device_tracker.aleix_mobil
  - name: Imma
    id: imma
    user_id: be173f93ffef481eba84dc6359ea6124

alarm_control_panel:
  - platform: manual
    name: home
    code: 1234

#google:
#  client_id: !secret google_oauth_calendar_id
#  client_secret: !secret google_oauth_calendar_secret

# Notifications

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_aleix
      - !secret telegram_chat_imma

notify:
  - name: "Xat Aleix"
    platform: telegram
    chat_id: !secret telegram_chat_aleix
  - name: "Xat Imma"
    platform: telegram
    chat_id: !secret telegram_chat_imma
  - name: "Grup casa"
    platform: telegram
    chat_id: !secret telegram_chat_casa

# Variables

input_text: !include devices/input_text.yaml

# Services

sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

ifttt:
  key: !secret ifttt_api_key

tts:
  - platform: google_translate
    service_name: google_say
    language: es

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  expose_by_default: true

wake_on_lan:

mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

speedtestdotnet:

map:

# Devices

cast:
  media_player:
    - host: !secret ip_chromecast
    - host: !secret ip_google_home

light: !include devices/lights.yaml
switch: !include devices/switches.yaml
sensor: !include devices/sensors.yaml
camera: !include devices/cameras.yaml
climate: !include devices/climates.yaml
media_player: !include devices/media_players.yaml

# Other config

scene: !include scenes.yaml
group: !include groups.yaml
automation: !include_dir_list automations/
script: !include_dir_merge_named scripts/
zone: !include zones.yaml
timer: !include timers.yaml
