# Config needed to work

homeassistant:
  name: Casa
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 102
  unit_system: metric
  time_zone: Europe/Madrid
  # customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp/

logger:
  default: info

config:

system_health:

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: aleix.casa
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1
  # ip_ban_enabled: true
  # login_attempts_threshold: 3

prometheus:
  namespace: hass
  component_config_glob:
    sensor.solar_angle:
      override_metric: sensor_unit_degrees

history:
  exclude:
    domains:
      - automation
      - script
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.internet_time
      - sensor.time
      - sensor.time_at_home
      - sensor.time_at_work
      - sensor.time_other
      - sensor.time_utc
      - sensor.mesa_percent
      - sensor.mesita_percent
      - sensor.sofa_percent
      - sensor.entrada_percent
      - sensor.cuina_temps_restant_percent
      - sensor.entrada_temps_restant_percent

recorder:
  db_url: !secret db_mysql_url
  purge_keep_days: 7
  purge_interval: 1

logbook:
  exclude:
    entity_globs:
      - binary_sensor.*_update_available
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.internet_time
      - sensor.time
      - sensor.time_at_home
      - sensor.time_at_work
      - sensor.time_other
      - sensor.time_utc
      - sensor.mesa_percent
      - sensor.mesita_percent
      - sensor.sofa_percent
      - sensor.entrada_percent
      - sensor.cuina_temps_restant_percent
      - sensor.entrada_temps_restant_percent

api:

auth:

duckdns:
  domain: hass-amurtra
  access_token: !secret duckdns_api_key

cloudflare:
  email: !secret cloudflare_email
  api_key: !secret cloudflare_token
  zone: aleix.cloud
  records:
    - casa.sys

lovelace:
  mode: yaml


person:
  - name: Aleix
    id: aleix
    user_id: 9b1b717615b5438b8f22bee0a1559b88
    device_trackers:
      - device_tracker.aleix_s10e
  - name: Imma
    id: imma
    user_id: 17da023a637a47d09761858054011d4b

alarm_control_panel:
  - platform: manual
    name: home
    code: 1234

# shopping_list:

#google:
#  client_id: !secret google_oauth_calendar_id
#  client_secret: !secret google_oauth_calendar_secret

# Notifications

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_aleix
      - !secret telegram_chat_imma

notify:
  - name: "Xat Aleix"
    platform: telegram
    chat_id: !secret telegram_chat_aleix
  - name: "Xat Imma"
    platform: telegram
    chat_id: !secret telegram_chat_imma
  - name: "Grup casa"
    platform: telegram
    chat_id: !secret telegram_chat_casa
  - name: Gotify high priority
    platform: rest
    resource: https://gotify.aleix.cloud/message
    method: POST_JSON
    headers:
      X-Gotify-Key: !secret gotify_key
    message_param_name: message
    title_param_name: title
    data:
      priority: 8

# Services

sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

ifttt:
  key: !secret ifttt_api_key

tts:
  - platform: google_translate
    service_name: google_say
    language: es

google_assistant:
  project_id: !secret google_project_id
  service_account: !include google-home-serviceaccount.json
  report_state: true
  expose_by_default: true

wake_on_lan:

mqtt:
  discovery: true
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

speedtestdotnet:

map:

browser_mod:

# o365:
#   client_secret: !secret o365_client_secret
#   client_id: !secret o365_client_id

calendar:
  - platform: ics
    calendars:
      - name: CAPSiDE Holidays
        url: !secret calendar_capside_holidays
        includeAllDay: true
      - name: CAPSiDE Oncall
        url: !secret calendar_capside_oncall
        includeAllDay: true
      - name: FCBarcelona matches
        url: !secret calendar_fcbarcelona
        includeAllDay: true

# Devices

# xiaomi_aqara:
#   discovery_retry: 10
#   gateways:
#     - key: !secret xiaomi_gateway_key
#       mac: !secret xiaomi_gateway_mac
#       host: !secret xiaomi_gateway_ip

cast:
  media_player:
    - host: !secret ip_chromecast
    - host: !secret ip_google_home

alexa: !include devices/alexa.yaml

webostv:
  host: !secret ip_tele_menjador
  name: Tele
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "A8-23-FE-27-CB-A5"

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

shell_command:
  aspirador_on: "/usr/local/bin/broadlink_cli --type 0x5f36 --host 192.168.4.3 --mac 89068e770f78 --send 26008a0062521031101110311011103111101031111010111011101010111011101011311031103111311031103210000453625210311011103110111031101110311011101110101011101110101110103111311031103210310e331000045361530f330e120f330e130e330e130e330e130e120f120e130e130f1110110f3210320f3210311131103111000d05000000000000000000000000"
  aspirador_off: "/usr/local/bin/broadlink_cli --type 0x5f36 --host 192.168.4.3 --mac 89068e770f78 --send 26008a005f540e330f120f320f120f330e120f330e330e130e120f120f120e130e120f120e330f330e330e330f330e000455625210311011103110111031101110311131101011101011101011101110101110311031113110311032100004536251113110111031101110310e130e3310320e1210111011101010111011101010320e330f330e330e3310000d05000000000000000000000000"
  aspirador_turbo: "/usr/local/bin/broadlink_cli --type 0x5f36 --host 192.168.4.3 --mac 89068e770f78 --send 26008a006152103111101032101010321010101110111031101110101110101110311131101011311031103210311000045362520e330f120e330f120e330f120f120e130e330e130e120f120e130e330e330f120f330e330e330f330e00045562520e330e130e330f120e330f120e130e120f330e120f120e130e120f330e330f120e330f330e330e330f000d05000000000000000000000000"
  tele_volume_up: "/usr/local/bin/broadlink_cli --type 0x5f36 --host 192.168.4.3 --mac 89068e770f78 --send 260050000001269610141114103a10141114101510151015103910391114103a1039103a1039103911141139101411141114101510151014113910151039103a10391039113910391100052d0001274b10000d05000000000000"
  tele_volume_down: "/usr/local/bin/broadlink_cli --type 0x5f36 --host 192.168.4.3 --mac 89068e770f78 --send 26005000000126951114101510391114101510151014111411391039101510391139103911391039103a103910151015101411141015101510141114103a1039103a1039103911391000052c0001284c10000d05000000000000"

remote:
- platform: broadlink
  host: !secret ip_remote
  mac: !secret mac_remote
  name: Broadlink IR

# Devices (external file)

light: !include devices/lights.yaml
switch: !include devices/switches.yaml
sensor: !include devices/sensors.yaml
binary_sensor: !include devices/binary_sensors.yaml
camera: !include devices/cameras.yaml
climate: !include devices/climates.yaml
media_player: !include devices/media_players.yaml


# Variables

input_text: !include devices/input_text.yaml
input_select: !include devices/input_select.yaml
input_boolean: !include devices/input_boolean.yaml
input_datetime: !include devices/input_datetime.yaml

# Other

scene: !include scenes.yaml
group: !include groups.yaml
automation: !include_dir_list automations/
script: !include_dir_merge_named scripts/
zone: !include zones.yaml
timer: !include timers.yaml
