- platform: webostv
  host: !secret ip_tele_menjador
  name: Tele
  filename: tele-menjador.conf
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "A8-23-FE-27-CB-A5"
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  aliases:
    8c841749fa5941dda9b54d94054769e0: 'Cuarto de estar'
