resources: !include lovelace/resources.yaml

custom_header: 
  header_text: Casa Immaleix
  compact_mode: true
  hide_tabs: mobile
  exceptions:
    - conditions:
        query_string: develop
    - conditions:
        user_agent: Mobile
      config:
        default_tab: mobile
        hide_tabs: home
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true

animated_background:
  default_url: /community_plugin/lovelace-animated-background/background-animations/sunny.html
  entity: "weather.dark_sky"
  state_url:
      'sunny': /community_plugin/lovelace-animated-background/background-animations/sunny.html
      'partlycloudy': /community_plugin/lovelace-animated-background/background-animations/cloudy.html
      'cloudy': /community_plugin/lovelace-animated-background/background-animations/cloudy.html
      'mostlycloudy': /community_plugin/lovelace-animated-background/background-animations/mostlycloudy.html
      'clear-night': /community_plugin/lovelace-animated-background/background-animations/night.html
      'fog': /community_plugin/lovelace-animated-background/background-animations/fog.html

decluttering_templates:
  nest_button: !include lovelace/decluttering_templates/nest_button.yaml
  nest_button_category: !include lovelace/decluttering_templates/nest_button_category.yaml
  nest_picture_button: !include lovelace/decluttering_templates/nest_picture_button.yaml

title: Casa
views:
  - !include lovelace/views/00_home_modern.yaml
  - !include lovelace/views/00_home_modern_mobile.yaml
  - !include lovelace/views/10_home_classic.yaml
  - !include lovelace/views/30_climates.yaml
  - !include lovelace/views/50_systems.yaml
