title: Casa
resources: !include lovelace/resources.yaml
preload:
  - conditional
custom_header: !include lovelace/custom_header.yaml
# animated_background: !include lovelace/animated_backgrounds.yaml
decluttering_templates: !include lovelace/decluttering_templates.yaml
views: !include lovelace/views.yaml