resources:
  - type: js
    url: /local/layout-card.js
  - type: js
    url: /local/vertical-stack-in-card.js?v=0.1.3
  - type: js
    url: /local/card-tools.js
  - type: js
    url: /local/custom_ui/weather-card.js
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
  - type: module
    url: /local/mini-media-player-bundle.js?v=1.1.3
  - type: module
    url: /local/mini-graph-card-bundle.js?v=0.4.2
  - type: module
    url: /local/simple-weather-card.bundle.js?v=0.3.0
  - type: module
    url: /local/simple-thermostat.js?v=1
  - type: module
    url: /local/compact-custom-header.js?v=0.0.1
  - type: module
    url: /local/button-card.js
  - type: js
    url: /local/card-mod.js?v=1
  - type: module
    url: /local/decluttering-card.js
  - type: js
    url: /local/nest-layout-card.js
  - type: module
    url: /local/weather-card-ws-mod.js
  - type: module
    url: /local/smhi-forecast-card.js
  - type: module
    url: /local/markdown-mod.js
  - type: module
    url: /local/atomic_calendar.js
cch:
  disable: false
  header: true
  menu: show
  sidebar_swipe: true
  notifications: show
  voice: hide
  options: clock
  clock_format: 24
  clock_date: true
  date_locale: es-CA
  swipe: true
  exceptions:
    - conditions:
        user: dashboard
      config:
        show_tabs: 10
        kiosk_mode: true
decluttering_templates:
  nest_button:
    card:
      entity: "[[entity]]"
      name: "[[name]]"
      show_icon: true
      show_last_changed: "[[show_last_changed]]"
      show_name: "[[show_name]]"
      show_state: "[[show_state]]"
      state: "[[state]]"
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
      tap_action:
        action: toggle
      hold_action:
        action: more-info
      type: "custom:button-card"
    default:
      - show_state: true
      - show_name: false
      - show_last_changed: true
  nest_button_info:
    card:
      entity: "[[entity]]"
      name: "[[name]]"
      show_icon: true
      show_last_changed: "[[show_last_changed]]"
      show_name: "[[show_name]]"
      show_state: "[[show_state]]"
      state: "[[state]]"
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
      tap_action:
        action: more-info
      type: "custom:button-card"
    default:
      - show_state: true
      - show_name: false
      - show_last_changed: true
  nest_button_service:
    card:
      entity: "[[entity]]"
      name: "[[name]]"
      show_icon: true
      show_last_changed: "[[show_last_changed]]"
      show_name: "[[show_name]]"
      show_state: "[[show_state]]"
      state: "[[state]]"
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
      tap_action:
        action: call-service
        service: [[service_id]]
        service_data: [[service_data]]
      hold_action:
        action: more-info
      type: "custom:button-card"
    default:
      - show_state: true
      - show_name: false
      - show_last_changed: true
  nest_picture_button:
    card:
      entity: "[[entity]]"
      entity_picture: "[[entity_picture]]"
      show_entity_picture: true
      show_icon: true
      show_name: false
      show_state: true
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        img {
          width: 100% !important;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
      tap_action:
        action: more-info
      type: "custom:button-card"
title: Casa
views:
  - !include lovelace/10_home_classic.yaml
  - !include lovelace/20_automations.yaml
  - !include lovelace/30_climates.yaml
  - !include lovelace/40_test.yaml
  - !include lovelace/00_home_modern.yaml
  - !include lovelace/00_home_modern_2.yaml
