alias: 22:00 - Turn on heater (bedroom)
initial_state: false
trigger:
- at: '21:00'
  platform: time
condition: []
action:
- data:
    entity_id: switch.calefaccio_dormitori
  service: switch.turn_on

