alias: 23:59 - Turn off heater (bedroom)
initial_state: true
trigger:
- at: '22:30'
  platform: time
condition: []
action:
- data:
    entity_id: switch.calefaccio_dormitori
  service: switch.turn_off

