alias: Menjador - Finestra oberta
trigger:
- entity_id: binary_sensor.window_dinningroom
  platform: state
  to: 'on'
  for: 
    seconds: 30
condition: []
action:
- service: climate.turn_off
  entity_id: climate.menjador