alias: Casa - Algú marxa
initial_state: true
mode: single
trigger:
  - entity_id: binary_sensor.door_main_entrance 
    from: 'off'
    platform: state
    to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.motion_entrance
  state: 'on'
action:
  # Send notification
  - service: notify.notify
    data: 
      title: "Casa"
      message: "Algú marxa de casa."
