- alias: "🚪 Entrada - Encendre llum amb moviment"
  id: "1615486961553204566"
  initial_state: true
  mode: restart
  trigger:
    - entity_id: binary_sensor.entrance_occupancy_1 
      platform: state
      to: 'on'
    - entity_id: binary_sensor.entrance_contact_1
      platform: state
      to: 'on'
  condition: []
  action:
  
    - choose:
      - conditions:
          condition: time
          after: "22:00:00"
          before: "00:00:00"
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.entrance_light_1
              brightness: 50
          - wait_template: "{{ is_state('binary_sensor.entrance_occupancy_1', 'off') }}"
            timeout: "00:01:00"
          - delay:
              minutes: 1
          - service: light.turn_off
            data:
              entity_id: light.entrance_light_1
              transition: 10
  
      - conditions:
          condition: time
          after: "07:00:00"
          before: "22:00:00"
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.entrance_light_1
              brightness: 250
          - wait_template: "{{ is_state('binary_sensor.entrance_occupancy_1', 'off') }}"
            timeout: "00:05:00"
          - delay:
              minutes: 5
          - service: light.turn_off
            data:
              entity_id: light.entrance_light_1
              transition: 10