alias: 'Calefacció dormitori - Configurar 19.0ºC'
initial_state: false
trigger:
  - platform: time
    at: "06:45:00"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: time
      after: "06:30:00"
    - condition: time
      before: "07:30:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.dormitori
      temperature: 19.0