alias: 'Purificador - LED on/off'
initial_state: true
trigger:
  - platform: time
    at: "23:30:00"
  - platform: time
    at: "09:00:00"
  - platform: homeassistant
    event: start
action:
  # Apaga el led per la nit
  - choose:
    - conditions:
        condition: time
        after: "23:30:00"
        before: "09:00:00"
      sequence:
        - service: xiaomi_miio.fan_set_led_off
          data:
            entity_id: fan.xiaomi_miio_device
    # Engega el led durant el dia
    default:
      - service: xiaomi_miio.fan_set_led_on
        data:
          entity_id: fan.xiaomi_miio_device
