alias: 'Calefacció despatx - Configurar 18.0ºC'
initial_state: true
trigger:
  - platform: time
    at: "17:00:00"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: time
      after: "15:00:00"
      before: "06:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.despatx
      temperature: 18.0