alias: 'Calefacció despatx - Configurar 19.5ºC'
initial_state: false
trigger:
  - platform: time
    at: "07:00:00"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: time
      after: "07:00:00"
      before: "15:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.despatx
      temperature: 19.5
