alias: 'Calefacció despatx - Apagar (feiners)'
initial_state: true
trigger:
  - platform: time
    at: "16:00:00"
  - platform: state
    entity_id: switch.calefaccio_menjador
    from: "on"
    to: "off"
condition:
  - condition: time
    after: "16:00:00"
    before: "15:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: calendar.festius_barcelona
    state: 'off'
  - condition: state
    entity_id: calendar.teleworking
    state: 'on'
action:
  - service: climate.turn_off
    entity_id: climate.despatx
