alias: Cuina - Apagar llum quan timer sigui 0
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.llum_cuina_timeout
condition: []
action:
- service: light.turn_off
  data:
    entity_id: light.encimera