alias: 'Start vacuum'
initial_state: true
trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.vacuum_schedule_time_mon', 'timestamp') | int | timestamp_custom('%H:%M', True)) }}"
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.vacuum_schedule_time_tue', 'timestamp') | int | timestamp_custom('%H:%M', True)) }}"
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.vacuum_schedule_time_wed', 'timestamp') | int | timestamp_custom('%H:%M', True)) }}"
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.vacuum_schedule_time_thu', 'timestamp') | int | timestamp_custom('%H:%M', True)) }}"
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.vacuum_schedule_time_fri', 'timestamp') | int | timestamp_custom('%H:%M', True)) }}"
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.vacuum_schedule_time_sat', 'timestamp') | int | timestamp_custom('%H:%M', True)) }}"
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.vacuum_schedule_time_sun', 'timestamp') | int | timestamp_custom('%H:%M', True)) }}"
condition:
  condition: or
  conditions:
    - condition: and
      conditions:
        - condition: time
          weekday: mon
        - condition: state
          entity_id: input_boolean.vacuum_enable_mon
          state: 'on'
    - condition: and
      conditions:
        - condition: time
          weekday: tue
        - condition: state
          entity_id: input_boolean.vacuum_enable_tue
          state: 'on'
    - condition: and
      conditions:
        - condition: time
          weekday: wed
        - condition: state
          entity_id: input_boolean.vacuum_enable_wed
          state: 'on'
    - condition: and
      conditions:
        - condition: time
          weekday: thu
        - condition: state
          entity_id: input_boolean.vacuum_enable_thu
          state: 'on'
    - condition: and
      conditions:
        - condition: time
          weekday: fri
        - condition: state
          entity_id: input_boolean.vacuum_enable_fri
          state: 'on'
    - condition: and
      conditions:
        - condition: time
          weekday: sat
        - condition: state
          entity_id: input_boolean.vacuum_enable_sat
          state: 'on'
    - condition: and
      conditions:
        - condition: time
          weekday: sun
        - condition: state
          entity_id: input_boolean.vacuum_enable_sun
          state: 'on'
action:
  # Start vacuum
  - service: shell_command.aspirador_on

  # Send notification
  - service: notify.gotify_high_priority
    data: 
      title: Aspirador
      message: S'ha activat l'aspirador

  # Wait 10 seconds
  - delay: '00:00:10'

  # Check if turbo must be enabled
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: time
            weekday: mon
          - condition: state
            entity_id: input_boolean.vacuum_enable_turbo_mon
            state: 'on'
      - condition: and
        conditions:
          - condition: time
            weekday: tue
          - condition: state
            entity_id: input_boolean.vacuum_enable_turbo_tue
            state: 'on'
      - condition: and
        conditions:
          - condition: time
            weekday: wed
          - condition: state
            entity_id: input_boolean.vacuum_enable_turbo_wed
            state: 'on'
      - condition: and
        conditions:
          - condition: time
            weekday: thu
          - condition: state
            entity_id: input_boolean.vacuum_enable_turbo_thu
            state: 'on'
      - condition: and
        conditions:
          - condition: time
            weekday: fri
          - condition: state
            entity_id: input_boolean.vacuum_enable_turbo_fri
            state: 'on'
      - condition: and
        conditions:
          - condition: time
            weekday: sat
          - condition: state
            entity_id: input_boolean.vacuum_enable_turbo_sat
            state: 'on'
      - condition: and
        conditions:
          - condition: time
            weekday: sun
          - condition: state
            entity_id: input_boolean.vacuum_enable_turbo_sun
            state: 'on'

  # Enable turbo
  - service: shell_command.aspirador_turbo

  # Send notification
  - service: notify.gotify_high_priority
    data: 
      title: Aspirador
      message: S'ha activat el mode TURBO
