alias: Entrada - Quan no hi hagi moviment, activar timer
initial_state: false
trigger:
- entity_id: binary_sensor.motion_entrance 
  from: 'on'
  platform: state
  to: 'off'
action:
- service: timer.start
  data:
    entity_id: timer.llum_entrada_timeout