alias: Entrada - Apagar llum quan timer sigui 0
initial_state: false
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.llum_entrada_timeout
condition: []
action:
- service: light.turn_off
  data:
    entity_id: light.entrada
    transition: 30