alias: "Track time from Home to Work"
initial_state: true
trigger:
  - platform: zone
    entity_id: device_tracker.aleix_mobil
    zone: zone.home
    event: leave
action:
  - service: timer.start
    entity_id: timer.time_from_home_to_work
  - wait_template: "{{ is_state('device_tracker.aleix_mobil', 'Feina') }}"
    timeout: "01:00:00"
    continue_on_timeout: "false"
  - service: timer.finish
    entity_id: timer.time_from_home_to_work
