alias: "Track test notification"
initial_state: false
trigger:
  - platform: zone
    entity_id: device_tracker.aleix_mobil
    zone: 
      - zone.home
      - zone.feina
    event: leave
  - platform: zone
    entity_id: device_tracker.aleix_mobil
    zone: 
      - zone.home
      - zone.feina
    event: enter
action:
  - data:
      message: "Aleix is now at: {{ states('person.aleix') }}."
      title: Movement
      target:
        - 475501
        - 417277407
    service: telegram_bot.send_message
