alias: "Track time from Work to Home"
initial_state: true
trigger:
  - platform: zone
    entity_id: device_tracker.aleix_mobil
    zone: zone.feina
    event: leave
action:
  - service: timer.start
    entity_id: timer.time_from_work_to_home
  - wait_template: "{{ is_state('device_tracker.aleix_mobil', 'home') }}"
    timeout: "01:00:00"
    continue_on_timeout: "false"
  - service: timer.finish
    entity_id: timer.time_from_work_to_home
