alias: "Track test notification"
initial_state: true
trigger:
  - platform: zone
    entity_id: device_tracker.aleix_mobil
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: device_tracker.aleix_mobil
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: device_tracker.aleix_mobil
    zone: zone.feina
    event: leave
  - platform: zone
    entity_id: device_tracker.aleix_mobil
    zone: zone.feina
    event: enter
action:
  - data:
      message: Aleix movements. {{ trigger.zone	}} changed from {{ trigger.from_state }} to {{ trigger.to_state	}}.
      title: Movement
      target:
        - 475501
        - 417277407
    service: telegram_bot.send_message
