alias: "Espia"
initial_state: true
trigger:
  - platform: zone
    entity_id:
      - device_tracker.sm_a405fn
      - device_tracker.sm_g970f
    zone:
      - zone.home
      - zone.ma ngo
      - zone.mercat_d_horta
    event: 
      - enter
      - leave
  # - platform: zone
  #   entity_id:
  #     - device_tracker.sm_a405fn
  #     - device_tracker.sm_g970f
  #   zone: zone.home
  #   event: enter
  # - platform: zone
  #   entity_id:
  #     - device_tracker.sm_a405fn
  #     - device_tracker.sm_g970f
  #   zone: zone.feina
  #   event: leave
  # - platform: zone
  #   entity_id:
  #     - device_tracker.sm_a405fn
  #     - device_tracker.sm_g970f
  #   zone: zone.feina
  #   event: enter
action:
  - service: notify.notify
    data:
      title: Espia
      message: "Aleix està a {{ states('person.aleix') }}, Imma està a {{ states('person.imma') }}"
