alias: Escala - Send photo
trigger:
- entity_id: binary_sensor.moviment_escala
  from: 'off'
  platform: state
  to: 'on'
condition: []
action:
- data:
    entity_id: camera.escala
    filename: /tmp/escala.jpg
  service: camera.snapshot
- delay: '3'
- data:
    file: /tmp/escala.jpg
    target:
    - 475501
    - 417277407
  service: telegram_bot.send_photo
- data:
    duration: '10'
    entity_id: camera.escala
    filename: /tmp/escala.mp4
  service: camera.record
- delay: '12'
- data:
    file: /tmp/escala.mp4
    target:
    - 475501
    - 417277407
  service: telegram_bot.send_video
