alias: "Light theme"
trigger:
  - platform: sun
    event: sunrise
    offset: "+00:01:00"
  - event: start
    platform: homeassistant
condition:
  - condition: sun
    after: sunrise
initial_state: true
action:
  - service: frontend.set_theme
    data:
      name: "Google Light Theme"
