- platform: generic_thermostat
  name: Menjador
  heater: switch.calefaccio_menjador
  target_sensor: sensor.livingroom_sensor_1_temperature
  min_temp: 7
  max_temp: 25
  ac_mode: false
  target_temp: 18.5
  cold_tolerance: 0.6
  hot_tolerance: 0.2
  min_cycle_duration:
    minutes: 30
  keep_alive:
    minutes: 15
  initial_hvac_mode: "off"
  precision: 0.1
- platform: generic_thermostat
  name: Dormitori
  heater: switch.bedroom_switch_heater
  target_sensor: sensor.bedroom_sensor_1_temperature
  min_temp: 7
  max_temp: 25
  ac_mode: false
  target_temp: 18.5
  cold_tolerance: 0.6
  hot_tolerance: 0.2
  min_cycle_duration:
    minutes: 30
  keep_alive:
    minutes: 15
  initial_hvac_mode: "off"
  precision: 0.1
- platform: generic_thermostat
  name: Despatx
  heater: switch.office_switch_heater
  target_sensor: sensor.office_sensor_1_temperature
  min_temp: 7
  max_temp: 25
  ac_mode: false
  target_temp: 18.5
  cold_tolerance: 0.6
  hot_tolerance: 0.2
  min_cycle_duration:
    minutes: 30
  keep_alive:
    minutes: 15
  initial_hvac_mode: "off"
  precision: 0.1
