- platform: generic_thermostat
  name: Menjador
  heater: switch.calefaccio_menjador
  target_sensor: sensor.menjador_temperature
  min_temp: 7
  max_temp: 25
  ac_mode: false
  target_temp: 18.5
  cold_tolerance: 0.6
  hot_tolerance: 0.2
  min_cycle_duration:
    minutes: 30
  keep_alive:
    minutes: 15
  initial_hvac_mode: "off"
  precision: 0.1
- platform: generic_thermostat
  name: Dormitori
  heater: switch.calefaccio_dormitori
  target_sensor: sensor.dormitori_temperature
  min_temp: 7
  max_temp: 25
  ac_mode: false
  target_temp: 18.5
  cold_tolerance: 0.6
  hot_tolerance: 0.2
  min_cycle_duration:
    minutes: 30
  keep_alive:
    minutes: 15
  initial_hvac_mode: "off"
  precision: 0.1
- platform: generic_thermostat
  name: Despatx
  heater: switch.calefaccio_despatx
  target_sensor: sensor.sensor_despatx_temperature
  min_temp: 7
  max_temp: 25
  ac_mode: false
  target_temp: 18.5
  cold_tolerance: 0.6
  hot_tolerance: 0.2
  min_cycle_duration:
    minutes: 30
  keep_alive:
    minutes: 15
  initial_hvac_mode: "off"
  precision: 0.1
