- platform: yr
# - platform: mqtt
#   name: Exterior Temperature
#   state_topic: "ble/exterior/temperature"
#   unit_of_measurement: "°C"
# - platform: mqtt
#   name: Exterior Humidity
#   state_topic: "ble/exterior/humidity"
#   unit_of_measurement: "%"
- platform: mitemp_bt
  mac: !secret mac_temp_mi_dormitori
  monitored_conditions:
    - temperature
    - humidity
  scan_interval: 60
  median: 1
  name: Dormitori
- platform: mitemp_bt
  mac: !secret mac_temp_mi_menjador
  monitored_conditions:
    - temperature
    - humidity
  scan_interval: 60
  median: 1
  name: Menjador
- platform: beewi_smartclim
  mac: !secret mac_temp_beewi_exterior
  name: Exterior
  scan_interval: 60
- platform: github
  access_token: !secret github_access_token
  repositories:
    - path: "alemuro/ha-conf"
- platform: waqi
  token: !secret waqi_api_key
  locations:
    - barcelona
- platform: google_travel_time
  scan_interval: 3600
  api_key: !secret google_api_key
  origin: !secret home_address
  destination: !secret work_address
  options:
    mode: driving
- platform: google_travel_time
  scan_interval: 3600
  api_key: !secret google_api_key
  origin: !secret home_address
  destination: !secret work_address
  options:
    mode: transit
    transit_mode: bus
- platform: history_stats
  name: Time at home
  entity_id: device_tracker.aleix_mobil
  state: "home"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Time at work
  entity_id: device_tracker.aleix_mobil
  state: "Feina"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Time other
  entity_id: device_tracker.aleix_mobil
  state: "fora"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"
- platform: time_date 
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
- platform: tmb
  app_id: 5c16345e
  app_key: 9d234e1b963e90908b9b09b093d2c475
  stops:
    - line: V25
      stop: 1051
      name: Casa
    - line: V25
      stop: 3258
      name: Feina