- platform: yr
- platform: mqtt
  name: Exterior Temperature
  state_topic: "ble/exterior/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  name: Exterior Humidity
  state_topic: "ble/exterior/humidity"
  unit_of_measurement: "%"
- platform: mitemp_bt
  mac: !secret mac_temp_mi_dormitori
  monitored_conditions:
    - temperature
    - humidity
  median: 1
  name: Dormitori
- platform: mitemp_bt
  mac: !secret mac_temp_mi_menjador
  monitored_conditions:
    - temperature
    - humidity
  median: 1
  name: Menjador
- platform: github
  access_token: !secret github_access_token
  repositories:
    - path: 'alemuro/ha-conf'
- platform: waqi
  token: !secret waqi_api_key
  locations:
    - barcelona
- platform: google_travel_time
  scan_interval: 3600
  api_key: !secret google_api_key
  origin: !secret home_address
  destination: !secret work_address
  options:
    mode: driving
- platform: google_travel_time
  scan_interval: 3600
  api_key: !secret google_api_key
  origin: !secret home_address
  destination: !secret work_address
  options:
    mode: transit
    transit_mode: bus

