alias: IFTTT - Sending event (calefaccions/menjador/on)
initial_state: true
trigger:
- payload: 'off'
  platform: mqtt
  topic: wifi/switch/calefaccions/menjador/set
condition: []
action:
- service: script.calefaccio_mejador_turn_off_mqtt