alias: IFTTT - Sending event (calefaccions/menjador/off)
initial_state: true
trigger:
- payload: 'on'
  platform: mqtt
  topic: wifi/switch/calefaccions/menjador/set
condition: []
action:
- service: script.calefaccio_mejador_turn_on_mqtt