- alias: "🖥️ Oficina - Encendre llum amb moviment"
  id: "1615486971610718094"
  initial_state: true
  mode: restart
  trigger:
    - entity_id: binary_sensor.office_occupancy_1_occupancy 
      platform: state
      to: 'on'
  condition:
    - condition: time
      after: "06:30:00"
    - condition: time
      before: "22:30:00"
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.office_light_2
          - light.office_light_1
    - wait_template: "{{ is_state('binary_sensor.office_occupancy_1_occupancy', 'off') }}"
    - delay:
        minutes: 10
    - service: light.turn_off
      data:
        entity_id: 
          - light.office_light_2
          - light.office_light_1