alias: Cuina - Encendre llum amb moviment
initial_state: false
trigger:
- entity_id: binary_sensor.motion_kitchen 
  from: 'off'
  platform: state
  to: 'on'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: 'input_select.home_mode'
    state: 'Normal'
  - condition: state
    entity_id: 'input_select.home_mode'
    state: 'Inactiu'
  - condition: state
    entity_id: 'input_select.home_mode'
    state: 'Fora de casa'
  - condition: state
    entity_id: 'input_select.home_mode'
    state: 'Simular activitat'
action:
- service: light.turn_on
  data:
    entity_id: switch.llum_cuina
- service: timer.cancel
  data:
    entity_id: timer.llum_cuina_timeout