alias: Activa escena "cine" quan es mira Netflix a la nit
initial_state: true
trigger:
  platform: template
  value_template: "{{ state_attr('media_player.tele','media_title') == 'Netflix' }}"
condition:
  - condition: time
    after: "22:00:00"
  - condition: time
    before: "23:59:00"
action:
  - service: scene.turn_on
    data:
      entity_id: scene.tele