alias: Off - Bedroom heater
initial_state: false
trigger:
- payload: 'off'
  platform: mqtt
  topic: wifi/switch/calefaccions/dormitori/set
condition: []
action:
- service: script.calefaccio_dormitori_turn_off_ifttt
