alias: Home Assistant - Started
trigger:
  - event: start
    platform: homeassistant
condition: []
action:
  - data:
      message: Home Assistant started
      title: Service alert!
      target:
        - 475501
        # - 417277407
    service: telegram_bot.send_message
initial_state: false
