alias: Set escena oficina
initial_state: true
trigger:
- platform: state
  entity_id: input_select.escena_oficina
condition: []
action:
- service: scene.turn_on
  data:
    entity_id: "scene.{{ states('input_select.escena_oficina') }}"
