alias: Menjador - Disminuir brillo
initial_state: true
trigger:
  - entity_id: sensor.comandament_menjador_action
    platform: state
    to: 'brightness_down_click'
action:
  - service: light.turn_on
    data_template: 
      entity_id: light.mesita
      brightness: "{{ [state_attr('light.mesita', 'brightness') | int - 50, 1] | max }}"
      transition: 1
  - service: light.turn_on
    data_template: 
      entity_id: light.mesa
      brightness: "{{ [state_attr('light.mesa', 'brightness') | int - 50, 1] | max }}"
      transition: 1
  - service: light.turn_on
    data_template: 
      entity_id: light.sofa
      brightness: "{{ [state_attr('light.sofa', 'brightness') | int - 50, 1] | max }}"
      transition: 1