alias: Menjador - Comandament toggle
initial_state: true
trigger:
  - entity_id: sensor.comandament_menjador_action
    platform: state
    to: 'toggle'
action:
  - service: light.toggle
    data_template: 
      entity_id: light.mesita
  - service: light.toggle
    data_template: 
      entity_id: light.sofa
  - service: light.toggle
    data_template: 
      entity_id: light.mesa