alias: Menjador - Fletxa esquerra
initial_state: true
trigger:
  - entity_id: sensor.comandament_menjador_action
    platform: state
    to: 'arrow_left_click'
condition:
  - condition: state
    entity_id: light.mesita
    state: 'on'
action:
  - service: light.turn_on
    data_template: 
      entity_id: light.mesita
      color_temp: "{{ [state_attr('light.mesita', 'color_temp') | int - 75, 250] | max }}"
      transition: 1