alias: 'Climate dormitori - Set 18.5 degrees'
initial_state: true
trigger:
  - platform: time
    at: "23:30:00"
  - platform: homeassistant
    event: start
condition:
  condition: or
  conditions:
    - condition: time
      after: "22:59:00"
    - condition: time
      before: "01:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.dormitori
      temperature: 18.5
