alias: Bedroom - Take action
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.sensor_finestra_habitacio_timeout
condition: []
action:
- service: climate.turn_off
  entity_id: climate.dormitori