alias: "Commute - Update morning commute sensor"
initial_state: 'on'
trigger:
  - platform: time_pattern
    minutes: '/10'
condition:
  - condition: time
    after: '07:45:00'
    before: '08:45:00'
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: homeassistant.update_entity
    entity_id: sensor.home_to_work_car
  - service: homeassistant.update_entity
    entity_id: sensor.home_to_work_bus