alias: 'Arbre Nadal - On'
initial_state: true
trigger:
  - platform: sun
    event: sunset
    offset: "00:05:00"
  - platform: homeassistant
    event: start
  - platform: zone
    entity_id:
      - person.imma
      - person.aleix
    event: enter
    zone: zone.home
condition:
  condition: and
  conditions:
    - condition: time
      after: "15:00:00"
    - condition: time
      before: "23:00:00"
    - condition: state
      entity_id: binary_sensor.someone_home
      state: "on"
action:
  - service: switch.turn_on
    data:
      entity_id: switch.arbre_nadal