alias: 'Arbre Nadal - Off'
initial_state: false
trigger:
  - platform: time
    at: "00:00:00"
  - platform: zone
    entity_id:
      - person.imma
      - person.aleix
    event: leave
    zone: zone.home
condition:
  condition: and
  conditions:
    - condition: time
      after: "23:00:00"
    - condition: time
      before: "9:00:00"
    - condition: state
      entity_id: binary_sensor.someone_home
      state: "off"
action:
  - service: switch.turn_off
    data:
      entity_id: switch.arbre_nadal