alias: On - IFTTT - Sending event (calefaccions/dormitori/off)
initial_state: true
trigger:
- payload: 'on'
  platform: mqtt
  topic: wifi/switch/calefaccions/dormitori/set
condition: 
- condition: state
  entity_id: switch.calefaccio_dormitori 
  state: 'off'
action:
- service: script.calefaccio_dormitori_turn_on
