alias: IFTTT - Sending event (calefaccions/dormitori/off)
initial_state: true
trigger:
- platform: state
  entity_id: switch.calefaccio_dormitori
  from: 'on'
  to: 'off'
condition: []
action:
- service: script.calefaccio_dormitori_turn_off
