alias: IFTTT - Sending event (calefaccions/menjador/on)
initial_state: true
trigger:
- platform: state
  entity_id: switch.calefaccio_menjador
  from: 'off'
  to: 'on'
condition: []
action:
- service: script.calefaccio_menjador_turn_on
