alias: On - Kitchen light
initial_state: true
trigger:
- payload: 'on'
  platform: mqtt
  topic: wifi/switch/cuina/set
condition: 
- condition: state
  entity_id: light.kitchen_light 
  state: 'off'
action:
- service: script.kitchen_light_turn_on
