alias: Off - Kichen light
initial_state: true
trigger:
- payload: 'off'
  platform: mqtt
  topic: wifi/switch/cuina/set
condition:
- condition: state
  entity_id: light.encimera
  state: 'on'
action:
- service: script.encimera_turn_off
