alias: 'Turn lights on when sun setting'
initial_state: true
trigger:
  - platform: sun
    event: sunset
    offset: "00:05:00"
condition:
  - condition: state
    entity_id: light.mesita
    state: 'off'
  - condition: state
    entity_id: binary_sensor.someone_home
    state: "on"
action:
  - service: light.turn_on
    entity_id: light.mesita 
    data:
      brightness: 10
      color_temp: 454
      transition: 30