alias: 'Turn lights on when sun setting'
initial_state: false
trigger:
  - platform: sun
    event: sunset
    offset: "00:05:00"
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: 
            - media_player.tele
            - switch.llum_cuina
            - light.entrada
            - light.mesa
            - light.sofa
          state: 
            - "on"
            - "playing"
action:
  - service: light.turn_on
    entity_id: light.entrada 
    data:
      transition: 30