alias: 'Turn lights on when sun setting'
initial_state: true
trigger:
  - platform: sun
    event: sunset
    offset: "00:05:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.mesita
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.tele
          state: 'playing'
        - condition: state
          entity_id: switch.llum_cuina
          state: 'on'
        - condition: state
          entity_id: light.entrada
          state: 'on'
        - condition: state
          entity_id: light.mesa
          state: 'on'
        - condition: state
          entity_id: light.sofa
          state: 'on'
action:
  - service: light.turn_on
    entity_id: light.mesita 
    data:
      brightness: 10
      color_temp: 454
      transition: 30