alias: 'Turn lights on when sun setting'
initial_state: true
trigger:
  - platform: sun
    event: sunset
    offset: "00:05:00"
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.tele
          state: 'playing'
        - condition: state
          entity_id: light.kitchen_light
          state: 'on'
        - condition: state
          entity_id: light.entrada
          state: 'on'
        - condition: state
          entity_id: light.mesa
          state: 'on'
        - condition: state
          entity_id: light.sofa
          state: 'on'
action:
  - service: light.turn_on
    entity_id: light.entrada 
    data:
      transition: 30