alias: Dinningroom - Close window
trigger:
- entity_id: binary_sensor.window_dinningroom
  from: 'on'
  platform: state
  to: 'off'
condition: []
action:
- service: timer.cancel
  data:
    entity_id: timer.sensor_finestra_menjador_timeout