alias: 'Arrocera arrencar segons programació'
initial_state: true
trigger:
  - platform: template
    value_template: |
      {{ 
        (states('sensor.time') == (state_attr('input_datetime.arrocera_schedule', 'timestamp') | int | timestamp_custom('%H:%M', False)))
      }}
condition:
  - condition: state
    entity_id: input_boolean.arrocera_enable
    state: "on"
action:
  # Start arrocera
  - service: switch.turn_on
    data:
      entity_id: switch.arbre_nadal

  # Send notification
  - service: notify.notify
    data: 
      title: Arrocera
      message: "S'ha activat l'arrocera"
